### ISSUE TITLE
Modify symbol data object

### ISSUE THREAD

**Issue by aaronrosenthal** [osisoft/PI-Coresight-Custom-Symbols#1]
Currently it is possible to drag attributes onto a symbol inside the Coresight UI to add new objects for the symbol to request data from. But is it possible to have the JavaScript code modify the data object directly? In other words, can I have my symbol automatically add a list of attributes during its init function?

**Comment by jgolla** [comment]
Right now it is not possible to modify the data object directly. We have been considering this, but were waiting for real world use cases before we implement it in the main PI Coresight product. 

If this is something you would like added in PI Coresight, I recommend adding it to the [PI Coresight Feedback page](https://osisoft.uservoice.com/forums/320517-pi-coresight).
