### ISSUE TITLE
Namespace no longer compatible with PI Coresight 2016 R2

### ISSUE THREAD

**Issue by jdryden-osi** [osisoft/PI-Coresight-Custom-Symbols#17]
When the namespaces were updated to PIVisualization, these examples will no longer work with Coresight 2016 R2 unless they are downloaded from a commit history before the namespace change, like this point from Jan 10:

https://github.com/osisoft/PI-Coresight-Custom-Symbols/tree/fbf8f7d21029ba42ba8add9fc6d88bee2504313d

Could we split a branch called "Coresight2016R2" and leave it behind so the master could continue to be updated but it is simpler for users to find the right version? Perhaps update the readme to instruct users how to get the proper version?

**Comment by jgolla** [comment]
Yes, we plan on doing that. If you take a look at the [Releases](https://github.com/osisoft/PI-Coresight-Custom-Symbols/releases) section you will see how we handled previous versions. Once PI Vision 2017 is released, we will update the master branch. We do have a [prerelease](https://github.com/osisoft/PI-Coresight-Custom-Symbols/tree/prerelease) branch as well that has the 2017 updates.

Is that what you are looking for?

**Comment by jdryden-osi** [comment]
That's perfect, thanks @jgolla !
