### ISSUE TITLE
Symbol doesn't show?

### ISSUE THREAD

**Issue by strauszz** [osisoft/PI-Coresight-Custom-Symbols#20]
I tried some samples (amchart) but the symbol didn't show on PI Coresight...
Element inspect showing:
Uncaught TypeError: Cannot read property 'Extensibility' of undefined
reference to:
CS.Extensibility.Enums.DatasourceBehaviors

Any idea?

**Comment by jgolla** [comment]
What version of PI Coresight are you using?

**Comment by strauszz** [comment]
2016 R2

**Comment by jgolla** [comment]
Which one specifically? It looks like I might have had a bad merge. At the bottom of the file it should pass window.Coresight into the IIFE (immediately executed functional expression). If it says PIVisualization, it was a bad merge.

**Comment by strauszz** [comment]
It was, PIVisualization. I changed back to windows.Coresight and its working good now... 

Thank you very much for your help @jgolla..

**Comment by RogerPalmen** [comment]
Hi, working through the AMcharts examples, the histogram, pie chart, radar chart, xyplot and trend are all still faulty.
So changing the return from window.PiVisualisation to window.Coresight (note the uppercase C!) fixes the issue.

**Comment by jgolla** [comment]
Sorry about this. I rolled back my bad merge. It should take care of all these issues now.
